export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_ERROR_RESPONSE = 'SET_ERROR_RESPONSE';
export const LOGIN_REDIRECT = 'LOGIN_REDIRECT';
export const EXAM_START_REDIRECT = 'EXAM_START_REDIRECT';
export const GET_ALL_EXAMS = 'GET_ALL_EXAMS';
export const SET_EXAM_QAS = 'SET_EXAM_QAS';
export const CLEAR_REDIRECTS = 'CLEAR_REDIRECTS';